# Generated by Django 4.1.2 on 2022-10-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0002_myotpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myotpmodel',
            name='otp',
            field=models.CharField(max_length=100),
        ),
    ]
